// WS9 BUG-186 — GENERATED FIXTURE, do not hand-edit.
//
// Every Ingredient.canonicalName in the cheese / egg / tofu / pasta families,
// as they exist in the catalog. Regenerate with:
//
//   node --env-file=.env --import tsx scripts/ws9-bug186-category-fix.ts --emit-fixture
//
// Its ONLY job is to make PREP_CATEGORY_OVERRIDE's keys falsifiable: the
// override table is keyed on ingredient NAME, so a canonical rename would
// silently unlink an entry and quietly restore the BUG-186 behaviour. The
// integrity test in prepCategoryOverride.test.ts asserts every key still
// appears here, so a rename goes RED instead of going unnoticed.
export const CATALOG_FAMILY_CANONICAL_NAMES: readonly string[] = [
  "acini di pepe pasta",
  "acini di pepe pasta (or orzo)",
  "american cheese",
  "american cheese slices",
  "angel hair pasta",
  "bean thread (glass) noodles",
  "block feta cheese",
  "blue cheese",
  "blue cheese crumbles",
  "blue cheese dressing",
  "brick cheese",
  "cavatappi pasta",
  "cheddar",
  "cheddar cheese",
  "cheese tortellini",
  "cheese whiz",
  "cotija cheese",
  "cotija cheese, crumbled",
  "cream cheese",
  "crumbled blue cheese",
  "crumbled cotija cheese",
  "crumbled feta cheese",
  "crumbled goat cheese",
  "crunchy chow mein noodles",
  "ditalini pasta",
  "dried flat rice noodles",
  "dried flat rice noodles (8mm wide)",
  "dried flat rice noodles (medium width, 3–5mm)",
  "dried lasagna sheets",
  "dried linguine",
  "dried pappardelle pasta",
  "dried rice noodles",
  "dried rice vermicelli noodles",
  "dried spaghetti",
  "dried sweet potato glass noodles (dangmyeon)",
  "dried tagliatelle",
  "dry lasagna sheets",
  "dry spaghetti",
  "egg",
  "egg noodles",
  "egg whites",
  "egg yolks",
  "eggplant",
  "elbow macaroni",
  "extra-firm tofu",
  "feta",
  "feta block",
  "feta cheese",
  "fettuccine",
  "finely grated parmesan",
  "finely grated parmesan cheese",
  "finely grated parmigiano-reggiano",
  "firm tofu",
  "flat rice noodles",
  "flat rice noodles (6–8 mm wide)",
  "flat rice noodles (6–8mm wide)",
  "flat rice noodles (medium width, 3mm)",
  "fontina",
  "fontina cheese",
  "fresh cheese ravioli",
  "fresh cheese tortellini",
  "fresh chinese wheat noodles",
  "fresh chow mein egg noodles",
  "fresh chow mein noodles",
  "fresh lo mein egg noodles",
  "fresh lo mein noodles",
  "fresh mozzarella",
  "fresh mozzarella cheese",
  "fresh or dried ramen noodles",
  "fresh ramen noodles",
  "fresh wide rice noodles",
  "fresh wide rice noodles (ho fun)",
  "fresh wide rice noodles (sen yai)",
  "fresh yakisoba noodles",
  "freshly grated parmesan",
  "freshly grated parmesan cheese",
  "freshly grated parmigiano-reggiano",
  "frozen potato and cheese pierogis",
  "globe eggplant",
  "gorgonzola dolce",
  "grated kefalotyri or parmesan cheese",
  "grated parmesan",
  "grated parmesan cheese",
  "grated pecorino romano",
  "gruyère cheese",
  "halloumi cheese",
  "hard-boiled eggs",
  "jumbo pasta shells",
  "large egg yolks",
  "large eggs",
  "lasagna noodles",
  "linguine",
  "low-moisture mozzarella",
  "low-moisture mozzarella cheese",
  "low-moisture whole-milk mozzarella",
  "manicotti pasta shells",
  "mexican cheese blend, shredded",
  "mexican crumbling cheese (cotija)",
  "monterey jack cheese",
  "mozzarella cheese",
  "oaxacan cheese",
  "oaxacan cheese (quesillo)",
  "oaxacan cheese or low-moisture mozzarella",
  "orecchiette pasta",
  "orzo",
  "orzo pasta",
  "paneer",
  "pappardelle",
  "parmesan",
  "parmesan cheese",
  "parmesan cheese, finely grated",
  "parmesan rind",
  "parmigiano reggiano",
  "parmigiano-reggiano",
  "parmigiano-reggiano rind",
  "parmigiano-reggiano, finely grated",
  "pasta cooking water",
  "pecorino romano",
  "pecorino romano cheese",
  "penne pasta",
  "penne rigate",
  "pepper jack cheese",
  "potato gnocchi",
  "provolone",
  "provolone cheese",
  "provolone cheese slices",
  "provolone cheese, sliced",
  "queso fresco",
  "ramen noodles",
  "refrigerated cheese tortellini",
  "reserved pasta cooking water",
  "rice noodles",
  "rice vermicelli",
  "rice vermicelli noodles",
  "rigatoni",
  "rigatoni pasta",
  "rotini pasta",
  "sharp cheddar",
  "sharp cheddar cheese",
  "sharp white cheddar cheese",
  "shaved parmesan",
  "shaved parmesan cheese",
  "shaved parmigiano-reggiano",
  "shelf-stable potato gnocchi",
  "shredded cheddar cheese",
  "shredded low-moisture mozzarella",
  "shredded low-moisture mozzarella cheese",
  "shredded low-moisture whole-milk mozzarella",
  "shredded mexican blend cheese",
  "shredded mexican cheese blend",
  "shredded monterey jack cheese",
  "shredded mozzarella cheese",
  "shredded oaxacan cheese",
  "shredded provolone",
  "shredded provolone cheese",
  "shredded sharp cheddar cheese",
  "shredded whole-milk mozzarella",
  "shredded whole-milk mozzarella cheese",
  "silken tofu",
  "sliced swiss cheese",
  "smoked gouda",
  "smoked gouda cheese",
  "spaghetti",
  "spaghetti squash",
  "swiss cheese",
  "swiss cheese slices",
  "thai eggplant",
  "vermicelli noodles",
  "whole milk mozzarella",
  "whole milk ricotta cheese",
  "whole-milk low-moisture mozzarella",
  "whole-milk mozzarella",
  "whole-milk ricotta",
  "whole-milk ricotta cheese",
  "wide dried rice noodles (sen yai or pad thai width)",
  "wide dried rice noodles (sen yai)",
  "wide egg noodles",
  "ziti pasta",
];
