// GENERATED — do not edit by hand.
// Source of truth: scripts/ws9-block3-target-dishes.csv
// Regenerate: node scripts/ws9-block3-gen-dishes.cjs
//
// Plan-Gen Arc · Block 3 (D-WS9-044) — the catalog spine. Each entry names a
// TARGET DISH (the main / centerpiece). The store-fill harness generates one
// complete dinner per entry, composing accompaniments around it. Ordered by
// rank; --limit N takes the first N by rank (the head, which users hit most).

export interface TargetDish {
  rank: number;
  dish: string;
  /** dishFamilyKey — stable slug of the dish; the harness dedups on this. */
  key: string;
  category: string;
}

export const TARGET_DISHES: TargetDish[] = [
  { rank: 1, dish: "Spaghetti with Meat Sauce", key: "spaghetti-with-meat-sauce", category: "Pasta" },
  { rank: 2, dish: "Ground Beef Tacos (Hard Shell)", key: "ground-beef-tacos-hard-shell", category: "Mexican/Tex-Mex" },
  { rank: 3, dish: "Baked Chicken Breast", key: "baked-chicken-breast", category: "Chicken" },
  { rank: 4, dish: "Classic Cheeseburger", key: "classic-cheeseburger", category: "Sandwiches/Burgers" },
  { rank: 5, dish: "Grilled Chicken Breast", key: "grilled-chicken-breast", category: "Chicken" },
  { rank: 6, dish: "Spaghetti and Meatballs", key: "spaghetti-and-meatballs", category: "Pasta" },
  { rank: 7, dish: "Beef Chili", key: "beef-chili", category: "Soups/Stews/Chili" },
  { rank: 8, dish: "Meatloaf", key: "meatloaf", category: "Beef" },
  { rank: 9, dish: "Chicken Parmesan", key: "chicken-parmesan", category: "Italian-American" },
  { rank: 10, dish: "Homemade Pepperoni Pizza", key: "homemade-pepperoni-pizza", category: "Pizza" },
  { rank: 11, dish: "Baked Mac and Cheese", key: "baked-mac-and-cheese", category: "Casseroles/Bakes" },
  { rank: 12, dish: "Beef and Broccoli Stir-Fry", key: "beef-and-broccoli-stir-fry", category: "Asian-American" },
  { rank: 13, dish: "Pot Roast", key: "pot-roast", category: "Beef" },
  { rank: 14, dish: "Sheet-Pan Chicken Fajitas", key: "sheet-pan-chicken-fajitas", category: "Mexican/Tex-Mex" },
  { rank: 15, dish: "Chicken and Vegetable Stir-Fry", key: "chicken-and-vegetable-stir-fry", category: "Asian-American" },
  { rank: 16, dish: "Baked Lemon-Herb Salmon", key: "baked-lemon-herb-salmon", category: "Seafood" },
  { rank: 17, dish: "Buttermilk Fried Chicken", key: "buttermilk-fried-chicken", category: "Chicken" },
  { rank: 18, dish: "Chicken Noodle Soup", key: "chicken-noodle-soup", category: "Soups/Stews/Chili" },
  { rank: 19, dish: "Roast Whole Chicken", key: "roast-whole-chicken", category: "Chicken" },
  { rank: 20, dish: "Beef Stew", key: "beef-stew", category: "Soups/Stews/Chili" },
  { rank: 21, dish: "Chicken Alfredo", key: "chicken-alfredo", category: "Pasta" },
  { rank: 22, dish: "Beef Lasagna", key: "beef-lasagna", category: "Italian-American" },
  { rank: 23, dish: "Grilled Pork Chops", key: "grilled-pork-chops", category: "Pork" },
  { rank: 24, dish: "BBQ Pulled Pork", key: "bbq-pulled-pork", category: "Pork" },
  { rank: 25, dish: "Sloppy Joes", key: "sloppy-joes", category: "Sandwiches/Burgers" },
  { rank: 26, dish: "Chicken Quesadillas", key: "chicken-quesadillas", category: "Mexican/Tex-Mex" },
  { rank: 27, dish: "Shrimp Scampi", key: "shrimp-scampi", category: "Seafood" },
  { rank: 28, dish: "Baked Ziti", key: "baked-ziti", category: "Italian-American" },
  { rank: 29, dish: "Turkey Burgers", key: "turkey-burgers", category: "Sandwiches/Burgers" },
  { rank: 30, dish: "Chicken Fried Rice", key: "chicken-fried-rice", category: "Asian-American" },
  { rank: 31, dish: "Chicken Tikka Masala", key: "chicken-tikka-masala", category: "Indian/South Asian" },
  { rank: 32, dish: "Beef Enchiladas", key: "beef-enchiladas", category: "Mexican/Tex-Mex" },
  { rank: 33, dish: "Chicken Enchiladas", key: "chicken-enchiladas", category: "Mexican/Tex-Mex" },
  { rank: 34, dish: "Sheet-Pan Sausage and Peppers", key: "sheet-pan-sausage-and-peppers", category: "Pork" },
  { rank: 35, dish: "Teriyaki Chicken", key: "teriyaki-chicken", category: "Asian-American" },
  { rank: 36, dish: "BBQ Baby Back Ribs", key: "bbq-baby-back-ribs", category: "Grilling/BBQ" },
  { rank: 37, dish: "Chicken Caesar Salad", key: "chicken-caesar-salad", category: "Salads/Bowls" },
  { rank: 38, dish: "Beef Stroganoff", key: "beef-stroganoff", category: "Beef" },
  { rank: 39, dish: "Chicken Pot Pie", key: "chicken-pot-pie", category: "Casseroles/Bakes" },
  { rank: 40, dish: "Buffalo Wings", key: "buffalo-wings", category: "Chicken" },
  { rank: 41, dish: "Grilled Sirloin Steak", key: "grilled-sirloin-steak", category: "Beef" },
  { rank: 42, dish: "Honey Garlic Chicken Thighs", key: "honey-garlic-chicken-thighs", category: "Chicken" },
  { rank: 43, dish: "Chicken Curry", key: "chicken-curry", category: "Indian/South Asian" },
  { rank: 44, dish: "Fish Tacos", key: "fish-tacos", category: "Mexican/Tex-Mex" },
  { rank: 45, dish: "Tuna Noodle Casserole", key: "tuna-noodle-casserole", category: "Casseroles/Bakes" },
  { rank: 46, dish: "Stuffed Bell Peppers", key: "stuffed-bell-peppers", category: "Casseroles/Bakes" },
  { rank: 47, dish: "Cheesy Chicken and Rice Casserole", key: "cheesy-chicken-and-rice-casserole", category: "Casseroles/Bakes" },
  { rank: 48, dish: "Spaghetti Carbonara", key: "spaghetti-carbonara", category: "Pasta" },
  { rank: 49, dish: "Smash Burgers", key: "smash-burgers", category: "Sandwiches/Burgers" },
  { rank: 50, dish: "Beef Burrito Bowls", key: "beef-burrito-bowls", category: "Mexican/Tex-Mex" },
  { rank: 51, dish: "Chicken Fajitas", key: "chicken-fajitas", category: "Mexican/Tex-Mex" },
  { rank: 52, dish: "Grilled Salmon", key: "grilled-salmon", category: "Seafood" },
  { rank: 53, dish: "Chicken Tenders", key: "chicken-tenders", category: "Chicken" },
  { rank: 54, dish: "Beef Fajitas", key: "beef-fajitas", category: "Mexican/Tex-Mex" },
  { rank: 55, dish: "Chili Mac", key: "chili-mac", category: "Soups/Stews/Chili" },
  { rank: 56, dish: "Chicken and Dumplings", key: "chicken-and-dumplings", category: "Soups/Stews/Chili" },
  { rank: 57, dish: "Baked Pork Chops", key: "baked-pork-chops", category: "Pork" },
  { rank: 58, dish: "General Tso's Chicken", key: "general-tso-s-chicken", category: "Asian-American" },
  { rank: 59, dish: "Orange Chicken", key: "orange-chicken", category: "Asian-American" },
  { rank: 60, dish: "Carnitas Tacos", key: "carnitas-tacos", category: "Mexican/Tex-Mex" },
  { rank: 61, dish: "Carne Asada Tacos", key: "carne-asada-tacos", category: "Mexican/Tex-Mex" },
  { rank: 62, dish: "Al Pastor Tacos", key: "al-pastor-tacos", category: "Mexican/Tex-Mex" },
  { rank: 63, dish: "Shrimp Tacos", key: "shrimp-tacos", category: "Mexican/Tex-Mex" },
  { rank: 64, dish: "Chicken Tacos", key: "chicken-tacos", category: "Mexican/Tex-Mex" },
  { rank: 65, dish: "Baked Bone-In Chicken Thighs", key: "baked-bone-in-chicken-thighs", category: "Chicken" },
  { rank: 66, dish: "Grilled Chicken Thighs", key: "grilled-chicken-thighs", category: "Chicken" },
  { rank: 67, dish: "Pan-Seared Ribeye Steak", key: "pan-seared-ribeye-steak", category: "Beef" },
  { rank: 68, dish: "Beef and Bean Burritos", key: "beef-and-bean-burritos", category: "Mexican/Tex-Mex" },
  { rank: 69, dish: "Chicken Burrito Bowls", key: "chicken-burrito-bowls", category: "Mexican/Tex-Mex" },
  { rank: 70, dish: "Baked Cod", key: "baked-cod", category: "Seafood" },
  { rank: 71, dish: "Salisbury Steak", key: "salisbury-steak", category: "Beef" },
  { rank: 72, dish: "Chicken Marsala", key: "chicken-marsala", category: "Italian-American" },
  { rank: 73, dish: "Chicken Piccata", key: "chicken-piccata", category: "Italian-American" },
  { rank: 74, dish: "Shepherd's Pie", key: "shepherd-s-pie", category: "Casseroles/Bakes" },
  { rank: 75, dish: "BBQ Chicken (Grilled)", key: "bbq-chicken-grilled", category: "Grilling/BBQ" },
  { rank: 76, dish: "Sesame Chicken", key: "sesame-chicken", category: "Asian-American" },
  { rank: 77, dish: "Sweet and Sour Chicken", key: "sweet-and-sour-chicken", category: "Asian-American" },
  { rank: 78, dish: "Chicken Lo Mein", key: "chicken-lo-mein", category: "Asian-American" },
  { rank: 79, dish: "Beef and Cheese Nachos", key: "beef-and-cheese-nachos", category: "Mexican/Tex-Mex" },
  { rank: 80, dish: "Turkey Meatballs", key: "turkey-meatballs", category: "Italian-American" },
  { rank: 81, dish: "Baked Tilapia", key: "baked-tilapia", category: "Seafood" },
  { rank: 82, dish: "Pork Tenderloin (Roasted)", key: "pork-tenderloin-roasted", category: "Pork" },
  { rank: 83, dish: "Chicken Cordon Bleu", key: "chicken-cordon-bleu", category: "Chicken" },
  { rank: 84, dish: "Meatball Subs", key: "meatball-subs", category: "Sandwiches/Burgers" },
  { rank: 85, dish: "Philly Cheesesteak", key: "philly-cheesesteak", category: "Sandwiches/Burgers" },
  { rank: 86, dish: "Beef Stir-Fry (Pepper Steak)", key: "beef-stir-fry-pepper-steak", category: "Asian-American" },
  { rank: 87, dish: "Chicken Tortilla Soup", key: "chicken-tortilla-soup", category: "Soups/Stews/Chili" },
  { rank: 88, dish: "Loaded Baked Potatoes", key: "loaded-baked-potatoes", category: "Sides/Bowls" },
  { rank: 89, dish: "Homemade Cheese Pizza", key: "homemade-cheese-pizza", category: "Pizza" },
  { rank: 90, dish: "Homemade Sausage Pizza", key: "homemade-sausage-pizza", category: "Pizza" },
  { rank: 91, dish: "BBQ Chicken Pizza", key: "bbq-chicken-pizza", category: "Pizza" },
  { rank: 92, dish: "Supreme Pizza", key: "supreme-pizza", category: "Pizza" },
  { rank: 93, dish: "Chicken and Broccoli Alfredo", key: "chicken-and-broccoli-alfredo", category: "Pasta" },
  { rank: 94, dish: "Baked Spaghetti", key: "baked-spaghetti", category: "Casseroles/Bakes" },
  { rank: 95, dish: "Penne alla Vodka", key: "penne-alla-vodka", category: "Pasta" },
  { rank: 96, dish: "Chicken Gyros", key: "chicken-gyros", category: "Greek/Mediterranean" },
  { rank: 97, dish: "Chicken Shawarma", key: "chicken-shawarma", category: "Middle Eastern" },
  { rank: 98, dish: "Beef Kebabs (Shish Kebab)", key: "beef-kebabs-shish-kebab", category: "Grilling/BBQ" },
  { rank: 99, dish: "Chicken Skewers (Kebabs)", key: "chicken-skewers-kebabs", category: "Grilling/BBQ" },
  { rank: 100, dish: "Pad Thai (Chicken)", key: "pad-thai-chicken", category: "Asian-American" },
  { rank: 101, dish: "Pad Thai (Shrimp)", key: "pad-thai-shrimp", category: "Asian-American" },
  { rank: 102, dish: "Kung Pao Chicken", key: "kung-pao-chicken", category: "Asian-American" },
  { rank: 103, dish: "Cashew Chicken", key: "cashew-chicken", category: "Asian-American" },
  { rank: 104, dish: "Mongolian Beef", key: "mongolian-beef", category: "Asian-American" },
  { rank: 105, dish: "Chicken Chow Mein", key: "chicken-chow-mein", category: "Asian-American" },
  { rank: 106, dish: "Beef Lo Mein", key: "beef-lo-mein", category: "Asian-American" },
  { rank: 107, dish: "Egg Roll in a Bowl", key: "egg-roll-in-a-bowl", category: "Asian-American" },
  { rank: 108, dish: "Grilled Cheese and Tomato Soup", key: "grilled-cheese-and-tomato-soup", category: "Soups/Stews/Chili" },
  { rank: 109, dish: "Broccoli Cheddar Soup", key: "broccoli-cheddar-soup", category: "Soups/Stews/Chili" },
  { rank: 110, dish: "Loaded Baked Potato Soup", key: "loaded-baked-potato-soup", category: "Soups/Stews/Chili" },
  { rank: 111, dish: "Minestrone Soup", key: "minestrone-soup", category: "Soups/Stews/Chili" },
  { rank: 112, dish: "Split Pea Soup with Ham", key: "split-pea-soup-with-ham", category: "Soups/Stews/Chili" },
  { rank: 113, dish: "White Chicken Chili", key: "white-chicken-chili", category: "Soups/Stews/Chili" },
  { rank: 114, dish: "Turkey Chili", key: "turkey-chili", category: "Soups/Stews/Chili" },
  { rank: 115, dish: "Vegetarian Chili", key: "vegetarian-chili", category: "Soups/Stews/Chili" },
  { rank: 116, dish: "Clam Chowder (New England)", key: "clam-chowder-new-england", category: "Soups/Stews/Chili" },
  { rank: 117, dish: "Chicken and Sausage Gumbo", key: "chicken-and-sausage-gumbo", category: "Soups/Stews/Chili" },
  { rank: 118, dish: "Jambalaya", key: "jambalaya", category: "Soups/Stews/Chili" },
  { rank: 119, dish: "Red Beans and Rice", key: "red-beans-and-rice", category: "Soups/Stews/Chili" },
  { rank: 120, dish: "Beef and Barley Soup", key: "beef-and-barley-soup", category: "Soups/Stews/Chili" },
  { rank: 121, dish: "Italian Wedding Soup", key: "italian-wedding-soup", category: "Soups/Stews/Chili" },
  { rank: 122, dish: "Butternut Squash Soup", key: "butternut-squash-soup", category: "Soups/Stews/Chili" },
  { rank: 123, dish: "Baked Salmon Teriyaki", key: "baked-salmon-teriyaki", category: "Seafood" },
  { rank: 124, dish: "Blackened Salmon", key: "blackened-salmon", category: "Seafood" },
  { rank: 125, dish: "Crab Cakes", key: "crab-cakes", category: "Seafood" },
  { rank: 126, dish: "Fried Shrimp", key: "fried-shrimp", category: "Seafood" },
  { rank: 127, dish: "Grilled Shrimp Skewers", key: "grilled-shrimp-skewers", category: "Seafood" },
  { rank: 128, dish: "Shrimp and Grits", key: "shrimp-and-grits", category: "Seafood" },
  { rank: 129, dish: "Shrimp Fried Rice", key: "shrimp-fried-rice", category: "Asian-American" },
  { rank: 130, dish: "Shrimp Stir-Fry", key: "shrimp-stir-fry", category: "Asian-American" },
  { rank: 131, dish: "Fish and Chips", key: "fish-and-chips", category: "Seafood" },
  { rank: 132, dish: "Tuna Steak (Seared)", key: "tuna-steak-seared", category: "Seafood" },
  { rank: 133, dish: "Lobster Mac and Cheese", key: "lobster-mac-and-cheese", category: "Casseroles/Bakes" },
  { rank: 134, dish: "Buffalo Chicken Mac and Cheese", key: "buffalo-chicken-mac-and-cheese", category: "Casseroles/Bakes" },
  { rank: 135, dish: "Stovetop Mac and Cheese", key: "stovetop-mac-and-cheese", category: "Casseroles/Bakes" },
  { rank: 136, dish: "Chicken Tetrazzini", key: "chicken-tetrazzini", category: "Casseroles/Bakes" },
  { rank: 137, dish: "King Ranch Chicken Casserole", key: "king-ranch-chicken-casserole", category: "Casseroles/Bakes" },
  { rank: 138, dish: "Hamburger Helper-Style Beef and Noodles", key: "hamburger-helper-style-beef-and-noodles", category: "Casseroles/Bakes" },
  { rank: 139, dish: "Tater Tot Casserole (Hotdish)", key: "tater-tot-casserole-hotdish", category: "Casseroles/Bakes" },
  { rank: 140, dish: "Enchilada Casserole", key: "enchilada-casserole", category: "Casseroles/Bakes" },
  { rank: 141, dish: "Chicken Broccoli Rice Casserole", key: "chicken-broccoli-rice-casserole", category: "Casseroles/Bakes" },
  { rank: 142, dish: "Poppy Seed Chicken Casserole", key: "poppy-seed-chicken-casserole", category: "Casseroles/Bakes" },
  { rank: 143, dish: "Beef Taco Casserole", key: "beef-taco-casserole", category: "Casseroles/Bakes" },
  { rank: 144, dish: "Chicken Enchilada Casserole", key: "chicken-enchilada-casserole", category: "Casseroles/Bakes" },
  { rank: 145, dish: "Sausage and Rice Casserole", key: "sausage-and-rice-casserole", category: "Casseroles/Bakes" },
  { rank: 146, dish: "Pork Carnitas (Bowls/Plates)", key: "pork-carnitas-bowls-plates", category: "Mexican/Tex-Mex" },
  { rank: 147, dish: "Chicken Tinga", key: "chicken-tinga", category: "Mexican/Tex-Mex" },
  { rank: 148, dish: "Beef Barbacoa", key: "beef-barbacoa", category: "Mexican/Tex-Mex" },
  { rank: 149, dish: "Chile Verde (Pork)", key: "chile-verde-pork", category: "Mexican/Tex-Mex" },
  { rank: 150, dish: "Chicken Chimichangas", key: "chicken-chimichangas", category: "Mexican/Tex-Mex" },
  { rank: 151, dish: "Beef Chimichangas", key: "beef-chimichangas", category: "Mexican/Tex-Mex" },
  { rank: 152, dish: "Chicken Tostadas", key: "chicken-tostadas", category: "Mexican/Tex-Mex" },
  { rank: 153, dish: "Tamales (Pork)", key: "tamales-pork", category: "Mexican/Tex-Mex" },
  { rank: 154, dish: "Beef Taquitos", key: "beef-taquitos", category: "Mexican/Tex-Mex" },
  { rank: 155, dish: "Chicken Flautas", key: "chicken-flautas", category: "Mexican/Tex-Mex" },
  { rank: 156, dish: "Carne Asada Plate", key: "carne-asada-plate", category: "Mexican/Tex-Mex" },
  { rank: 157, dish: "Fajita Bowls", key: "fajita-bowls", category: "Mexican/Tex-Mex" },
  { rank: 158, dish: "Elote-Style Chicken Bowls", key: "elote-style-chicken-bowls", category: "Mexican/Tex-Mex" },
  { rank: 159, dish: "Birria Tacos", key: "birria-tacos", category: "Mexican/Tex-Mex" },
  { rank: 160, dish: "Baked Chicken Drumsticks", key: "baked-chicken-drumsticks", category: "Chicken" },
  { rank: 161, dish: "BBQ Chicken Drumsticks", key: "bbq-chicken-drumsticks", category: "Chicken" },
  { rank: 162, dish: "Chicken and Waffles (dinner)", key: "chicken-and-waffles-dinner", category: "Chicken" },
  { rank: 163, dish: "Nashville Hot Chicken", key: "nashville-hot-chicken", category: "Chicken" },
  { rank: 164, dish: "Chicken Nuggets (Homemade)", key: "chicken-nuggets-homemade", category: "Chicken" },
  { rank: 165, dish: "Popcorn Chicken", key: "popcorn-chicken", category: "Chicken" },
  { rank: 166, dish: "Chicken Schnitzel", key: "chicken-schnitzel", category: "Chicken" },
  { rank: 167, dish: "Smothered Chicken", key: "smothered-chicken", category: "Chicken" },
  { rank: 168, dish: "Chicken and Gravy over Biscuits", key: "chicken-and-gravy-over-biscuits", category: "Chicken" },
  { rank: 169, dish: "Lemon Pepper Chicken", key: "lemon-pepper-chicken", category: "Chicken" },
  { rank: 170, dish: "Garlic Butter Chicken Bites", key: "garlic-butter-chicken-bites", category: "Chicken" },
  { rank: 171, dish: "Chicken Cacciatore", key: "chicken-cacciatore", category: "Italian-American" },
  { rank: 172, dish: "Chicken Saltimbocca", key: "chicken-saltimbocca", category: "Italian-American" },
  { rank: 173, dish: "Chicken Francese", key: "chicken-francese", category: "Italian-American" },
  { rank: 174, dish: "Chicken Scampi", key: "chicken-scampi", category: "Italian-American" },
  { rank: 175, dish: "Rotisserie-Style Chicken", key: "rotisserie-style-chicken", category: "Chicken" },
  { rank: 176, dish: "Beer Can Chicken", key: "beer-can-chicken", category: "Grilling/BBQ" },
  { rank: 177, dish: "Spatchcock Grilled Chicken", key: "spatchcock-grilled-chicken", category: "Grilling/BBQ" },
  { rank: 178, dish: "Grilled Whole Chicken", key: "grilled-whole-chicken", category: "Grilling/BBQ" },
  { rank: 179, dish: "Chicken Souvlaki", key: "chicken-souvlaki", category: "Greek/Mediterranean" },
  { rank: 180, dish: "Greek Chicken (Sheet Pan)", key: "greek-chicken-sheet-pan", category: "Greek/Mediterranean" },
  { rank: 181, dish: "Chicken Shawarma Bowls", key: "chicken-shawarma-bowls", category: "Middle Eastern" },
  { rank: 182, dish: "Falafel (Plate/Wrap)", key: "falafel-plate-wrap", category: "Middle Eastern" },
  { rank: 183, dish: "Beef Kofta (Kebabs)", key: "beef-kofta-kebabs", category: "Middle Eastern" },
  { rank: 184, dish: "Butter Chicken", key: "butter-chicken", category: "Indian/South Asian" },
  { rank: 185, dish: "Chicken Biryani", key: "chicken-biryani", category: "Indian/South Asian" },
  { rank: 186, dish: "Chana Masala", key: "chana-masala", category: "Indian/South Asian" },
  { rank: 187, dish: "Dal (Lentil Curry)", key: "dal-lentil-curry", category: "Indian/South Asian" },
  { rank: 188, dish: "Palak Paneer", key: "palak-paneer", category: "Indian/South Asian" },
  { rank: 189, dish: "Chicken Korma", key: "chicken-korma", category: "Indian/South Asian" },
  { rank: 190, dish: "Lamb/Beef Curry", key: "lamb-beef-curry", category: "Indian/South Asian" },
  { rank: 191, dish: "Vegetable Curry", key: "vegetable-curry", category: "Indian/South Asian" },
  { rank: 192, dish: "Chicken Vindaloo", key: "chicken-vindaloo", category: "Indian/South Asian" },
  { rank: 193, dish: "Saag Chicken", key: "saag-chicken", category: "Indian/South Asian" },
  { rank: 194, dish: "Thai Green Curry (Chicken)", key: "thai-green-curry-chicken", category: "Asian-American" },
  { rank: 195, dish: "Thai Red Curry (Chicken)", key: "thai-red-curry-chicken", category: "Asian-American" },
  { rank: 196, dish: "Thai Red Curry (Shrimp)", key: "thai-red-curry-shrimp", category: "Asian-American" },
  { rank: 197, dish: "Panang Curry", key: "panang-curry", category: "Asian-American" },
  { rank: 198, dish: "Thai Basil Chicken (Pad Krapow)", key: "thai-basil-chicken-pad-krapow", category: "Asian-American" },
  { rank: 199, dish: "Drunken Noodles (Pad See Ew?)", key: "drunken-noodles-pad-see-ew", category: "Asian-American" },
  { rank: 200, dish: "Pad See Ew", key: "pad-see-ew", category: "Asian-American" },
  { rank: 201, dish: "Beef and Snow Pea Stir-Fry", key: "beef-and-snow-pea-stir-fry", category: "Asian-American" },
  { rank: 202, dish: "Cashew Shrimp", key: "cashew-shrimp", category: "Asian-American" },
  { rank: 203, dish: "Honey Walnut Shrimp", key: "honey-walnut-shrimp", category: "Asian-American" },
  { rank: 204, dish: "Kung Pao Shrimp", key: "kung-pao-shrimp", category: "Asian-American" },
  { rank: 205, dish: "Szechuan Beef", key: "szechuan-beef", category: "Asian-American" },
  { rank: 206, dish: "Sweet and Sour Pork", key: "sweet-and-sour-pork", category: "Asian-American" },
  { rank: 207, dish: "Char Siu (BBQ Pork)", key: "char-siu-bbq-pork", category: "Asian-American" },
  { rank: 208, dish: "Chicken Katsu", key: "chicken-katsu", category: "Asian-American" },
  { rank: 209, dish: "Katsu Curry (Chicken)", key: "katsu-curry-chicken", category: "Asian-American" },
  { rank: 210, dish: "Teriyaki Salmon Bowl", key: "teriyaki-salmon-bowl", category: "Asian-American" },
  { rank: 211, dish: "Poke Bowl (Tuna)", key: "poke-bowl-tuna", category: "Asian-American" },
  { rank: 212, dish: "Bibimbap", key: "bibimbap", category: "Asian-American" },
  { rank: 213, dish: "Korean Beef Bowl (Ground)", key: "korean-beef-bowl-ground", category: "Asian-American" },
  { rank: 214, dish: "Bulgogi (Korean BBQ Beef)", key: "bulgogi-korean-bbq-beef", category: "Asian-American" },
  { rank: 215, dish: "Korean Fried Chicken", key: "korean-fried-chicken", category: "Asian-American" },
  { rank: 216, dish: "Chicken Adobo", key: "chicken-adobo", category: "Asian-American" },
  { rank: 217, dish: "Beef and Vegetable Ramen (Homemade)", key: "beef-and-vegetable-ramen-homemade", category: "Asian-American" },
  { rank: 218, dish: "Miso-Glazed Salmon", key: "miso-glazed-salmon", category: "Asian-American" },
  { rank: 219, dish: "Vegetable Fried Rice", key: "vegetable-fried-rice", category: "Asian-American" },
  { rank: 220, dish: "Vegetable Lo Mein", key: "vegetable-lo-mein", category: "Asian-American" },
  { rank: 221, dish: "Tofu Stir-Fry", key: "tofu-stir-fry", category: "Asian-American" },
  { rank: 222, dish: "General Tso's Tofu", key: "general-tso-s-tofu", category: "Asian-American" },
  { rank: 223, dish: "Dumplings/Potstickers (Pan-Fried)", key: "dumplings-potstickers-pan-fried", category: "Asian-American" },
  { rank: 224, dish: "Fried Rice with Egg (Yang Chow)", key: "fried-rice-with-egg-yang-chow", category: "Asian-American" },
  { rank: 225, dish: "Baked Ham", key: "baked-ham", category: "Pork" },
  { rank: 226, dish: "Ham and Scalloped Potatoes", key: "ham-and-scalloped-potatoes", category: "Casseroles/Bakes" },
  { rank: 227, dish: "Pork Schnitzel", key: "pork-schnitzel", category: "Pork" },
  { rank: 228, dish: "Breaded Pork Chops", key: "breaded-pork-chops", category: "Pork" },
  { rank: 229, dish: "Smothered Pork Chops", key: "smothered-pork-chops", category: "Pork" },
  { rank: 230, dish: "Stuffed Pork Chops", key: "stuffed-pork-chops", category: "Pork" },
  { rank: 231, dish: "Pork Milanese", key: "pork-milanese", category: "Pork" },
  { rank: 232, dish: "Pork Carnitas Bowls", key: "pork-carnitas-bowls", category: "Mexican/Tex-Mex" },
  { rank: 233, dish: "Cuban Mojo Pork", key: "cuban-mojo-pork", category: "Pork" },
  { rank: 234, dish: "Kalua Pork", key: "kalua-pork", category: "Pork" },
  { rank: 235, dish: "Bratwurst and Sauerkraut", key: "bratwurst-and-sauerkraut", category: "Pork" },
  { rank: 236, dish: "Italian Sausage and Peppers", key: "italian-sausage-and-peppers", category: "Pork" },
  { rank: 237, dish: "Kielbasa and Cabbage", key: "kielbasa-and-cabbage", category: "Pork" },
  { rank: 238, dish: "Bacon-Wrapped Pork Tenderloin", key: "bacon-wrapped-pork-tenderloin", category: "Pork" },
  { rank: 239, dish: "Pork Fried Rice", key: "pork-fried-rice", category: "Asian-American" },
  { rank: 240, dish: "Pork Ramen (Homemade)", key: "pork-ramen-homemade", category: "Asian-American" },
  { rank: 241, dish: "St. Louis Ribs (Grilled)", key: "st-louis-ribs-grilled", category: "Grilling/BBQ" },
  { rank: 242, dish: "Beef Brisket (Smoked/Braised)", key: "beef-brisket-smoked-braised", category: "Grilling/BBQ" },
  { rank: 243, dish: "Grilled Ribeye", key: "grilled-ribeye", category: "Grilling/BBQ" },
  { rank: 244, dish: "Grilled T-Bone/Porterhouse", key: "grilled-t-bone-porterhouse", category: "Grilling/BBQ" },
  { rank: 245, dish: "Grilled Flank Steak", key: "grilled-flank-steak", category: "Grilling/BBQ" },
  { rank: 246, dish: "Grilled Skirt Steak", key: "grilled-skirt-steak", category: "Grilling/BBQ" },
  { rank: 247, dish: "Steak Fajita Bowls", key: "steak-fajita-bowls", category: "Mexican/Tex-Mex" },
  { rank: 248, dish: "Steak and Potatoes", key: "steak-and-potatoes", category: "Beef" },
  { rank: 249, dish: "Steak au Poivre", key: "steak-au-poivre", category: "Beef" },
  { rank: 250, dish: "Steak Diane", key: "steak-diane", category: "Beef" },
  { rank: 251, dish: "Beef Tips and Gravy over Rice", key: "beef-tips-and-gravy-over-rice", category: "Beef" },
  { rank: 252, dish: "Beef and Noodles", key: "beef-and-noodles", category: "Beef" },
  { rank: 253, dish: "Swedish Meatballs", key: "swedish-meatballs", category: "Beef" },
  { rank: 254, dish: "Porcupine Meatballs", key: "porcupine-meatballs", category: "Beef" },
  { rank: 255, dish: "BBQ Meatballs", key: "bbq-meatballs", category: "Beef" },
  { rank: 256, dish: "Beef and Bean Chili Dogs", key: "beef-and-bean-chili-dogs", category: "Sandwiches/Burgers" },
  { rank: 257, dish: "Corn Dogs (Homemade)", key: "corn-dogs-homemade", category: "Sandwiches/Burgers" },
  { rank: 258, dish: "Hamburger Steak with Onions", key: "hamburger-steak-with-onions", category: "Beef" },
  { rank: 259, dish: "French Dip Sandwich", key: "french-dip-sandwich", category: "Sandwiches/Burgers" },
  { rank: 260, dish: "Italian Beef Sandwich", key: "italian-beef-sandwich", category: "Sandwiches/Burgers" },
  { rank: 261, dish: "Roast Beef Sandwich (Hot)", key: "roast-beef-sandwich-hot", category: "Sandwiches/Burgers" },
  { rank: 262, dish: "Beef Barbacoa Tacos", key: "beef-barbacoa-tacos", category: "Mexican/Tex-Mex" },
  { rank: 263, dish: "Corned Beef and Cabbage", key: "corned-beef-and-cabbage", category: "Beef" },
  { rank: 264, dish: "Beef Short Ribs (Braised)", key: "beef-short-ribs-braised", category: "Beef" },
  { rank: 265, dish: "Braised Beef Ragu", key: "braised-beef-ragu", category: "Italian-American" },
  { rank: 266, dish: "Baked Meatballs (Italian)", key: "baked-meatballs-italian", category: "Italian-American" },
  { rank: 267, dish: "Chicken Parm Sub", key: "chicken-parm-sub", category: "Sandwiches/Burgers" },
  { rank: 268, dish: "Eggplant Parmesan", key: "eggplant-parmesan", category: "Italian-American" },
  { rank: 269, dish: "Chicken Florentine", key: "chicken-florentine", category: "Italian-American" },
  { rank: 270, dish: "Fettuccine Alfredo (Plain)", key: "fettuccine-alfredo-plain", category: "Pasta" },
  { rank: 271, dish: "Shrimp Alfredo", key: "shrimp-alfredo", category: "Pasta" },
  { rank: 272, dish: "Cajun Chicken Pasta", key: "cajun-chicken-pasta", category: "Pasta" },
  { rank: 273, dish: "Buffalo Chicken Pasta", key: "buffalo-chicken-pasta", category: "Pasta" },
  { rank: 274, dish: "Pesto Pasta (with Chicken)", key: "pesto-pasta-with-chicken", category: "Pasta" },
  { rank: 275, dish: "Pesto Pasta (Plain)", key: "pesto-pasta-plain", category: "Pasta" },
  { rank: 276, dish: "Pasta Primavera", key: "pasta-primavera", category: "Pasta" },
  { rank: 277, dish: "Cacio e Pepe", key: "cacio-e-pepe", category: "Pasta" },
  { rank: 278, dish: "Aglio e Olio", key: "aglio-e-olio", category: "Pasta" },
  { rank: 279, dish: "Sausage and Peppers Pasta", key: "sausage-and-peppers-pasta", category: "Pasta" },
  { rank: 280, dish: "One-Pot Taco Pasta", key: "one-pot-taco-pasta", category: "Pasta" },
  { rank: 281, dish: "Stuffed Shells", key: "stuffed-shells", category: "Italian-American" },
  { rank: 282, dish: "Manicotti", key: "manicotti", category: "Italian-American" },
  { rank: 283, dish: "Ravioli (Cheese) with Marinara", key: "ravioli-cheese-with-marinara", category: "Italian-American" },
  { rank: 284, dish: "Tortellini Alfredo", key: "tortellini-alfredo", category: "Pasta" },
  { rank: 285, dish: "Tortellini in Tomato Cream", key: "tortellini-in-tomato-cream", category: "Pasta" },
  { rank: 286, dish: "Gnocchi with Marinara", key: "gnocchi-with-marinara", category: "Italian-American" },
  { rank: 287, dish: "Gnocchi with Brown Butter and Sage", key: "gnocchi-with-brown-butter-and-sage", category: "Italian-American" },
  { rank: 288, dish: "Baked Gnocchi (Cheesy)", key: "baked-gnocchi-cheesy", category: "Italian-American" },
  { rank: 289, dish: "Lasagna Roll-Ups", key: "lasagna-roll-ups", category: "Italian-American" },
  { rank: 290, dish: "White Chicken Lasagna", key: "white-chicken-lasagna", category: "Italian-American" },
  { rank: 291, dish: "Vegetable Lasagna", key: "vegetable-lasagna", category: "Italian-American" },
  { rank: 292, dish: "Chicken Tortellini Soup", key: "chicken-tortellini-soup", category: "Soups/Stews/Chili" },
  { rank: 293, dish: "Pasta e Fagioli", key: "pasta-e-fagioli", category: "Soups/Stews/Chili" },
  { rank: 294, dish: "Zuppa Toscana", key: "zuppa-toscana", category: "Soups/Stews/Chili" },
  { rank: 295, dish: "Lasagna Soup", key: "lasagna-soup", category: "Soups/Stews/Chili" },
  { rank: 296, dish: "Honey Garlic Salmon", key: "honey-garlic-salmon", category: "Seafood" },
  { rank: 297, dish: "Cajun Shrimp Pasta", key: "cajun-shrimp-pasta", category: "Pasta" },
  { rank: 298, dish: "Shrimp Boil", key: "shrimp-boil", category: "Seafood" },
  { rank: 299, dish: "Cioppino", key: "cioppino", category: "Soups/Stews/Chili" },
  { rank: 300, dish: "Fish Fry (Fried Cod/Perch)", key: "fish-fry-fried-cod-perch", category: "Seafood" },
  { rank: 301, dish: "Baked Stuffed Flounder", key: "baked-stuffed-flounder", category: "Seafood" },
  { rank: 302, dish: "Salmon Patties/Croquettes", key: "salmon-patties-croquettes", category: "Seafood" },
  { rank: 303, dish: "Tuna Melt", key: "tuna-melt", category: "Sandwiches/Burgers" },
  { rank: 304, dish: "Lobster Rolls", key: "lobster-rolls", category: "Sandwiches/Burgers" },
  { rank: 305, dish: "Scallops (Seared)", key: "scallops-seared", category: "Seafood" },
  { rank: 306, dish: "Mussels (Steamed, White Wine)", key: "mussels-steamed-white-wine", category: "Seafood" },
  { rank: 307, dish: "Grilled Mahi-Mahi", key: "grilled-mahi-mahi", category: "Seafood" },
  { rank: 308, dish: "Fish en Papillote", key: "fish-en-papillote", category: "Seafood" },
  { rank: 309, dish: "Blackened Catfish", key: "blackened-catfish", category: "Seafood" },
  { rank: 310, dish: "Fried Catfish", key: "fried-catfish", category: "Seafood" },
  { rank: 311, dish: "Chicken Burrito", key: "chicken-burrito", category: "Mexican/Tex-Mex" },
  { rank: 312, dish: "Wet Burrito", key: "wet-burrito", category: "Mexican/Tex-Mex" },
  { rank: 313, dish: "Nachos Supreme (Chicken)", key: "nachos-supreme-chicken", category: "Mexican/Tex-Mex" },
  { rank: 314, dish: "Taco Salad", key: "taco-salad", category: "Salads/Bowls" },
  { rank: 315, dish: "Southwest Chicken Salad", key: "southwest-chicken-salad", category: "Salads/Bowls" },
  { rank: 316, dish: "Cobb Salad", key: "cobb-salad", category: "Salads/Bowls" },
  { rank: 317, dish: "Chicken Bacon Ranch Salad", key: "chicken-bacon-ranch-salad", category: "Salads/Bowls" },
  { rank: 318, dish: "Buffalo Chicken Salad", key: "buffalo-chicken-salad", category: "Salads/Bowls" },
  { rank: 319, dish: "Greek Salad with Chicken", key: "greek-salad-with-chicken", category: "Salads/Bowls" },
  { rank: 320, dish: "Steak Salad", key: "steak-salad", category: "Salads/Bowls" },
  { rank: 321, dish: "Shrimp Caesar Salad", key: "shrimp-caesar-salad", category: "Salads/Bowls" },
  { rank: 322, dish: "Chef Salad", key: "chef-salad", category: "Salads/Bowls" },
  { rank: 323, dish: "Grain Bowl (Chicken and Veg)", key: "grain-bowl-chicken-and-veg", category: "Salads/Bowls" },
  { rank: 324, dish: "Burrito Bowl (Vegetarian)", key: "burrito-bowl-vegetarian", category: "Salads/Bowls" },
  { rank: 325, dish: "Buddha Bowl (Roasted Veg)", key: "buddha-bowl-roasted-veg", category: "Salads/Bowls" },
  { rank: 326, dish: "Falafel Bowl", key: "falafel-bowl", category: "Salads/Bowls" },
  { rank: 327, dish: "Teriyaki Tofu Bowl", key: "teriyaki-tofu-bowl", category: "Salads/Bowls" },
  { rank: 328, dish: "Sushi Bowl (Salmon/Tuna)", key: "sushi-bowl-salmon-tuna", category: "Salads/Bowls" },
  { rank: 329, dish: "Chicken Shawarma Plate", key: "chicken-shawarma-plate", category: "Middle Eastern" },
  { rank: 330, dish: "Beef Gyros", key: "beef-gyros", category: "Greek/Mediterranean" },
  { rank: 331, dish: "Chicken Souvlaki Bowls", key: "chicken-souvlaki-bowls", category: "Greek/Mediterranean" },
  { rank: 332, dish: "Greek Chicken Bowls", key: "greek-chicken-bowls", category: "Greek/Mediterranean" },
  { rank: 333, dish: "Spanakopita (as main)", key: "spanakopita-as-main", category: "Greek/Mediterranean" },
  { rank: 334, dish: "Stuffed Grape Leaves (Dolmas)", key: "stuffed-grape-leaves-dolmas", category: "Greek/Mediterranean" },
  { rank: 335, dish: "Moussaka", key: "moussaka", category: "Greek/Mediterranean" },
  { rank: 336, dish: "Shakshuka (dinner)", key: "shakshuka-dinner", category: "Middle Eastern" },
  { rank: 337, dish: "Hummus Bowl with Chicken", key: "hummus-bowl-with-chicken", category: "Middle Eastern" },
  { rank: 338, dish: "Kofta over Rice", key: "kofta-over-rice", category: "Middle Eastern" },
  { rank: 339, dish: "Tabbouleh with Grilled Chicken", key: "tabbouleh-with-grilled-chicken", category: "Middle Eastern" },
  { rank: 340, dish: "Vegetable Stir-Fry over Rice", key: "vegetable-stir-fry-over-rice", category: "Asian-American" },
  { rank: 341, dish: "Sesame Tofu", key: "sesame-tofu", category: "Asian-American" },
  { rank: 342, dish: "Kung Pao Tofu", key: "kung-pao-tofu", category: "Asian-American" },
  { rank: 343, dish: "Mapo Tofu", key: "mapo-tofu", category: "Asian-American" },
  { rank: 344, dish: "Tofu Pad Thai", key: "tofu-pad-thai", category: "Asian-American" },
  { rank: 345, dish: "Vegetable Pad Thai", key: "vegetable-pad-thai", category: "Asian-American" },
  { rank: 346, dish: "Vegetable Curry over Rice", key: "vegetable-curry-over-rice", category: "Asian-American" },
  { rank: 347, dish: "Chickpea Coconut Curry", key: "chickpea-coconut-curry", category: "Indian/South Asian" },
  { rank: 348, dish: "Aloo Gobi", key: "aloo-gobi", category: "Indian/South Asian" },
  { rank: 349, dish: "Vegetable Biryani", key: "vegetable-biryani", category: "Indian/South Asian" },
  { rank: 350, dish: "Paneer Tikka Masala", key: "paneer-tikka-masala", category: "Indian/South Asian" },
  { rank: 351, dish: "Lentil Dal with Rice", key: "lentil-dal-with-rice", category: "Indian/South Asian" },
  { rank: 352, dish: "Black Bean Burgers", key: "black-bean-burgers", category: "Sandwiches/Burgers" },
  { rank: 353, dish: "Portobello Mushroom Burgers", key: "portobello-mushroom-burgers", category: "Sandwiches/Burgers" },
  { rank: 354, dish: "Veggie Burgers (Bean/Grain)", key: "veggie-burgers-bean-grain", category: "Sandwiches/Burgers" },
  { rank: 355, dish: "Lentil Loaf", key: "lentil-loaf", category: "Vegetarian/Vegan" },
  { rank: 356, dish: "Stuffed Portobello Mushrooms", key: "stuffed-portobello-mushrooms", category: "Vegetarian/Vegan" },
  { rank: 357, dish: "Eggplant Rollatini", key: "eggplant-rollatini", category: "Italian-American" },
  { rank: 358, dish: "Ratatouille", key: "ratatouille", category: "Vegetarian/Vegan" },
  { rank: 359, dish: "Vegetable Enchiladas", key: "vegetable-enchiladas", category: "Mexican/Tex-Mex" },
  { rank: 360, dish: "Black Bean Tacos", key: "black-bean-tacos", category: "Mexican/Tex-Mex" },
  { rank: 361, dish: "Sweet Potato and Black Bean Tacos", key: "sweet-potato-and-black-bean-tacos", category: "Mexican/Tex-Mex" },
  { rank: 362, dish: "Cauliflower Tacos", key: "cauliflower-tacos", category: "Mexican/Tex-Mex" },
  { rank: 363, dish: "Bean and Cheese Burritos", key: "bean-and-cheese-burritos", category: "Mexican/Tex-Mex" },
  { rank: 364, dish: "Vegetarian Fajitas", key: "vegetarian-fajitas", category: "Mexican/Tex-Mex" },
  { rank: 365, dish: "Stuffed Sweet Potatoes", key: "stuffed-sweet-potatoes", category: "Vegetarian/Vegan" },
  { rank: 366, dish: "Stuffed Zucchini Boats", key: "stuffed-zucchini-boats", category: "Vegetarian/Vegan" },
  { rank: 367, dish: "Stuffed Cabbage Rolls", key: "stuffed-cabbage-rolls", category: "Casseroles/Bakes" },
  { rank: 368, dish: "Stuffed Acorn Squash", key: "stuffed-acorn-squash", category: "Vegetarian/Vegan" },
  { rank: 369, dish: "Vegetable Pot Pie", key: "vegetable-pot-pie", category: "Casseroles/Bakes" },
  { rank: 370, dish: "Broccoli Cheese Rice Bake", key: "broccoli-cheese-rice-bake", category: "Casseroles/Bakes" },
  { rank: 371, dish: "Vegetable Stir-Fry Noodles", key: "vegetable-stir-fry-noodles", category: "Asian-American" },
  { rank: 372, dish: "Cauliflower Fried Rice", key: "cauliflower-fried-rice", category: "Asian-American" },
  { rank: 373, dish: "Zucchini Noodles with Marinara", key: "zucchini-noodles-with-marinara", category: "Italian-American" },
  { rank: 374, dish: "Spaghetti Squash with Marinara", key: "spaghetti-squash-with-marinara", category: "Italian-American" },
  { rank: 375, dish: "Baked Ziti (Vegetarian)", key: "baked-ziti-vegetarian", category: "Italian-American" },
  { rank: 376, dish: "Margherita Flatbread", key: "margherita-flatbread", category: "Pizza" },
  { rank: 377, dish: "Buffalo Chicken Pizza", key: "buffalo-chicken-pizza", category: "Pizza" },
  { rank: 378, dish: "Hawaiian Pizza", key: "hawaiian-pizza", category: "Pizza" },
  { rank: 379, dish: "Meat Lovers Pizza", key: "meat-lovers-pizza", category: "Pizza" },
  { rank: 380, dish: "White Pizza (Ricotta/Garlic)", key: "white-pizza-ricotta-garlic", category: "Pizza" },
  { rank: 381, dish: "Veggie Pizza", key: "veggie-pizza", category: "Pizza" },
  { rank: 382, dish: "Detroit-Style Pizza", key: "detroit-style-pizza", category: "Pizza" },
  { rank: 383, dish: "Deep-Dish Pizza", key: "deep-dish-pizza", category: "Pizza" },
  { rank: 384, dish: "Naan Pizza", key: "naan-pizza", category: "Pizza" },
  { rank: 385, dish: "French Bread Pizza", key: "french-bread-pizza", category: "Pizza" },
  { rank: 386, dish: "Calzone", key: "calzone", category: "Italian-American" },
  { rank: 387, dish: "Stromboli", key: "stromboli", category: "Italian-American" },
  { rank: 388, dish: "Homemade Hot Dogs (Loaded)", key: "homemade-hot-dogs-loaded", category: "Sandwiches/Burgers" },
  { rank: 389, dish: "Chicago-Style Hot Dog", key: "chicago-style-hot-dog", category: "Sandwiches/Burgers" },
  { rank: 390, dish: "Chili Cheese Dog", key: "chili-cheese-dog", category: "Sandwiches/Burgers" },
  { rank: 391, dish: "Bratwurst on a Bun", key: "bratwurst-on-a-bun", category: "Sandwiches/Burgers" },
  { rank: 392, dish: "Pulled Pork Sandwich", key: "pulled-pork-sandwich", category: "Sandwiches/Burgers" },
  { rank: 393, dish: "BBQ Chicken Sandwich", key: "bbq-chicken-sandwich", category: "Sandwiches/Burgers" },
  { rank: 394, dish: "Fried Chicken Sandwich (Classic)", key: "fried-chicken-sandwich-classic", category: "Sandwiches/Burgers" },
  { rank: 395, dish: "Spicy Fried Chicken Sandwich", key: "spicy-fried-chicken-sandwich", category: "Sandwiches/Burgers" },
  { rank: 396, dish: "Grilled Chicken Sandwich", key: "grilled-chicken-sandwich", category: "Sandwiches/Burgers" },
  { rank: 397, dish: "Chicken Bacon Ranch Wrap", key: "chicken-bacon-ranch-wrap", category: "Sandwiches/Burgers" },
  { rank: 398, dish: "Buffalo Chicken Wrap", key: "buffalo-chicken-wrap", category: "Sandwiches/Burgers" },
  { rank: 399, dish: "BLT", key: "blt", category: "Sandwiches/Burgers" },
  { rank: 400, dish: "Club Sandwich", key: "club-sandwich", category: "Sandwiches/Burgers" },
  { rank: 401, dish: "Reuben", key: "reuben", category: "Sandwiches/Burgers" },
  { rank: 402, dish: "Patty Melt", key: "patty-melt", category: "Sandwiches/Burgers" },
  { rank: 403, dish: "Juicy Lucy (Stuffed Burger)", key: "juicy-lucy-stuffed-burger", category: "Sandwiches/Burgers" },
  { rank: 404, dish: "Bacon Cheeseburger", key: "bacon-cheeseburger", category: "Sandwiches/Burgers" },
  { rank: 405, dish: "Mushroom Swiss Burger", key: "mushroom-swiss-burger", category: "Sandwiches/Burgers" },
  { rank: 406, dish: "Pub/Gourmet Burger", key: "pub-gourmet-burger", category: "Sandwiches/Burgers" },
  { rank: 407, dish: "Salmon Burger", key: "salmon-burger", category: "Sandwiches/Burgers" },
  { rank: 408, dish: "Sliders (Beef)", key: "sliders-beef", category: "Sandwiches/Burgers" },
  { rank: 409, dish: "Meatball Sliders", key: "meatball-sliders", category: "Sandwiches/Burgers" },
  { rank: 410, dish: "Pulled Pork Sliders", key: "pulled-pork-sliders", category: "Sandwiches/Burgers" },
  { rank: 411, dish: "Sheet-Pan Chicken and Potatoes", key: "sheet-pan-chicken-and-potatoes", category: "Chicken" },
  { rank: 412, dish: "Sheet-Pan Chicken and Broccoli", key: "sheet-pan-chicken-and-broccoli", category: "Chicken" },
  { rank: 413, dish: "Sheet-Pan Salmon and Asparagus", key: "sheet-pan-salmon-and-asparagus", category: "Seafood" },
  { rank: 414, dish: "Sheet-Pan Shrimp Boil", key: "sheet-pan-shrimp-boil", category: "Seafood" },
  { rank: 415, dish: "Sheet-Pan Steak and Veggies", key: "sheet-pan-steak-and-veggies", category: "Beef" },
  { rank: 416, dish: "Sheet-Pan Pork Chops and Apples", key: "sheet-pan-pork-chops-and-apples", category: "Pork" },
  { rank: 417, dish: "Sheet-Pan Meatballs and Veg", key: "sheet-pan-meatballs-and-veg", category: "Beef" },
  { rank: 418, dish: "Sheet-Pan Gnocchi and Veg", key: "sheet-pan-gnocchi-and-veg", category: "Italian-American" },
  { rank: 419, dish: "Chicken and Vegetable Skewers", key: "chicken-and-vegetable-skewers", category: "Grilling/BBQ" },
  { rank: 420, dish: "Grilled Vegetable Kebabs", key: "grilled-vegetable-kebabs", category: "Grilling/BBQ" },
  { rank: 421, dish: "Grilled Corn and Chicken Plate", key: "grilled-corn-and-chicken-plate", category: "Grilling/BBQ" },
  { rank: 422, dish: "Grilled Bratwurst and Peppers", key: "grilled-bratwurst-and-peppers", category: "Grilling/BBQ" },
  { rank: 423, dish: "Grilled Shrimp Tacos", key: "grilled-shrimp-tacos", category: "Mexican/Tex-Mex" },
  { rank: 424, dish: "Grilled Portobello Steaks", key: "grilled-portobello-steaks", category: "Grilling/BBQ" },
  { rank: 425, dish: "Grilled Salmon Salad", key: "grilled-salmon-salad", category: "Salads/Bowls" },
  { rank: 426, dish: "Turkey Meatloaf", key: "turkey-meatloaf", category: "Beef" },
  { rank: 427, dish: "Turkey Tacos", key: "turkey-tacos", category: "Mexican/Tex-Mex" },
  { rank: 428, dish: "Turkey Chili Mac", key: "turkey-chili-mac", category: "Soups/Stews/Chili" },
  { rank: 429, dish: "Turkey Tetrazzini", key: "turkey-tetrazzini", category: "Casseroles/Bakes" },
  { rank: 430, dish: "Roast Turkey Breast", key: "roast-turkey-breast", category: "Chicken" },
  { rank: 431, dish: "Turkey and Stuffing (Weeknight)", key: "turkey-and-stuffing-weeknight", category: "Casseroles/Bakes" },
  { rank: 432, dish: "Ground Turkey Skillet with Rice", key: "ground-turkey-skillet-with-rice", category: "Chicken" },
  { rank: 433, dish: "Turkey Sloppy Joes", key: "turkey-sloppy-joes", category: "Sandwiches/Burgers" },
  { rank: 434, dish: "Turkey Bolognese", key: "turkey-bolognese", category: "Pasta" },
  { rank: 435, dish: "Chicken Sausage and Peppers", key: "chicken-sausage-and-peppers", category: "Chicken" },
  { rank: 436, dish: "Chicken Sausage Pasta", key: "chicken-sausage-pasta", category: "Pasta" },
  { rank: 437, dish: "Andouille and Shrimp Skillet", key: "andouille-and-shrimp-skillet", category: "Seafood" },
  { rank: 438, dish: "Cajun Sausage and Rice", key: "cajun-sausage-and-rice", category: "Soups/Stews/Chili" },
  { rank: 439, dish: "Dirty Rice", key: "dirty-rice", category: "Soups/Stews/Chili" },
  { rank: 440, dish: "Étouffée (Crawfish/Shrimp)", key: "touff-e-crawfish-shrimp", category: "Soups/Stews/Chili" },
  { rank: 441, dish: "Chicken and Rice Soup", key: "chicken-and-rice-soup", category: "Soups/Stews/Chili" },
  { rank: 442, dish: "Beef Vegetable Soup", key: "beef-vegetable-soup", category: "Soups/Stews/Chili" },
  { rank: 443, dish: "Hamburger Soup", key: "hamburger-soup", category: "Soups/Stews/Chili" },
  { rank: 444, dish: "Taco Soup", key: "taco-soup", category: "Soups/Stews/Chili" },
  { rank: 445, dish: "Potato Leek Soup", key: "potato-leek-soup", category: "Soups/Stews/Chili" },
  { rank: 446, dish: "Tomato Basil Soup", key: "tomato-basil-soup", category: "Soups/Stews/Chili" },
  { rank: 447, dish: "French Onion Soup", key: "french-onion-soup", category: "Soups/Stews/Chili" },
  { rank: 448, dish: "Chicken Pho", key: "chicken-pho", category: "Asian-American" },
  { rank: 449, dish: "Beef Pho", key: "beef-pho", category: "Asian-American" },
  { rank: 450, dish: "Wonton Soup", key: "wonton-soup", category: "Asian-American" },
  { rank: 451, dish: "Hot and Sour Soup", key: "hot-and-sour-soup", category: "Asian-American" },
  { rank: 452, dish: "Egg Drop Soup", key: "egg-drop-soup", category: "Asian-American" },
  { rank: 453, dish: "Ramen (Miso, Homemade)", key: "ramen-miso-homemade", category: "Asian-American" },
  { rank: 454, dish: "Tom Kha Gai", key: "tom-kha-gai", category: "Asian-American" },
  { rank: 455, dish: "Tortilla Soup (Vegetarian)", key: "tortilla-soup-vegetarian", category: "Soups/Stews/Chili" },
  { rank: 456, dish: "Black Bean Soup", key: "black-bean-soup", category: "Soups/Stews/Chili" },
  { rank: 457, dish: "Lentil Soup", key: "lentil-soup", category: "Soups/Stews/Chili" },
  { rank: 458, dish: "Chicken Enchilada Soup", key: "chicken-enchilada-soup", category: "Soups/Stews/Chili" },
  { rank: 459, dish: "Cheeseburger Soup", key: "cheeseburger-soup", category: "Soups/Stews/Chili" },
  { rank: 460, dish: "Ham and Bean Soup", key: "ham-and-bean-soup", category: "Soups/Stews/Chili" },
  { rank: 461, dish: "Chicken Gnocchi Soup", key: "chicken-gnocchi-soup", category: "Soups/Stews/Chili" },
  { rank: 462, dish: "Beef Bourguignon", key: "beef-bourguignon", category: "Beef" },
  { rank: 463, dish: "Coq au Vin", key: "coq-au-vin", category: "Chicken" },
  { rank: 464, dish: "Chicken Fricassee", key: "chicken-fricassee", category: "Chicken" },
  { rank: 465, dish: "Beef Wellington", key: "beef-wellington", category: "Beef" },
  { rank: 466, dish: "Braised Lamb Shanks", key: "braised-lamb-shanks", category: "Lamb" },
  { rank: 467, dish: "Rack of Lamb (Roasted)", key: "rack-of-lamb-roasted", category: "Lamb" },
  { rank: 468, dish: "Lamb Chops (Grilled)", key: "lamb-chops-grilled", category: "Lamb" },
  { rank: 469, dish: "Gyro Plate (Lamb)", key: "gyro-plate-lamb", category: "Greek/Mediterranean" },
  { rank: 470, dish: "Shepherd's Pie (Beef/Cottage)", key: "shepherd-s-pie-beef-cottage", category: "Casseroles/Bakes" },
  { rank: 471, dish: "Frito Pie", key: "frito-pie", category: "Casseroles/Bakes" },
  { rank: 472, dish: "Chili Cheese Fries", key: "chili-cheese-fries", category: "Sides/Bowls" },
  { rank: 473, dish: "Loaded Nachos (Vegetarian)", key: "loaded-nachos-vegetarian", category: "Mexican/Tex-Mex" },
  { rank: 474, dish: "Quesadilla (Cheese)", key: "quesadilla-cheese", category: "Mexican/Tex-Mex" },
  { rank: 475, dish: "Steak Quesadilla", key: "steak-quesadilla", category: "Mexican/Tex-Mex" },
  { rank: 476, dish: "Shrimp Quesadilla", key: "shrimp-quesadilla", category: "Mexican/Tex-Mex" },
  { rank: 477, dish: "Chicken Divan", key: "chicken-divan", category: "Casseroles/Bakes" },
  { rank: 478, dish: "Hot Brown (Kentucky)", key: "hot-brown-kentucky", category: "Sandwiches/Burgers" },
  { rank: 479, dish: "Turkey Pot Pie", key: "turkey-pot-pie", category: "Casseroles/Bakes" },
  { rank: 480, dish: "Chicken à la King", key: "chicken-la-king", category: "Chicken" },
  { rank: 481, dish: "Chicken and Stuffing Casserole", key: "chicken-and-stuffing-casserole", category: "Casseroles/Bakes" },
  { rank: 482, dish: "Johnny Marzetti", key: "johnny-marzetti", category: "Casseroles/Bakes" },
  { rank: 483, dish: "Goulash (American)", key: "goulash-american", category: "Beef" },
  { rank: 484, dish: "Hungarian Goulash", key: "hungarian-goulash", category: "Soups/Stews/Chili" },
  { rank: 485, dish: "Pierogi with Onions", key: "pierogi-with-onions", category: "Vegetarian/Vegan" },
  { rank: 486, dish: "Kielbasa and Pierogi", key: "kielbasa-and-pierogi", category: "Pork" },
  { rank: 487, dish: "Cabbage and Sausage Skillet", key: "cabbage-and-sausage-skillet", category: "Pork" },
  { rank: 488, dish: "Fried Rice (Kimchi)", key: "fried-rice-kimchi", category: "Asian-American" },
  { rank: 489, dish: "Bibimbap (Tofu)", key: "bibimbap-tofu", category: "Asian-American" },
  { rank: 490, dish: "Japchae", key: "japchae", category: "Asian-American" },
  { rank: 491, dish: "Yakisoba (Chicken)", key: "yakisoba-chicken", category: "Asian-American" },
  { rank: 492, dish: "Chow Fun (Beef)", key: "chow-fun-beef", category: "Asian-American" },
  { rank: 493, dish: "Singapore Noodles", key: "singapore-noodles", category: "Asian-American" },
  { rank: 494, dish: "Dan Dan Noodles", key: "dan-dan-noodles", category: "Asian-American" },
  { rank: 495, dish: "Beef and Bean Tostadas", key: "beef-and-bean-tostadas", category: "Mexican/Tex-Mex" },
  { rank: 496, dish: "Enfrijoladas", key: "enfrijoladas", category: "Mexican/Tex-Mex" },
  { rank: 497, dish: "Sopes", key: "sopes", category: "Mexican/Tex-Mex" },
  { rank: 498, dish: "Chilaquiles (dinner)", key: "chilaquiles-dinner", category: "Mexican/Tex-Mex" },
  { rank: 499, dish: "Pozole (Pork/Chicken)", key: "pozole-pork-chicken", category: "Soups/Stews/Chili" },
  { rank: 500, dish: "Menudo", key: "menudo", category: "Soups/Stews/Chili" },
  { rank: 501, dish: "Caldo de Pollo", key: "caldo-de-pollo", category: "Soups/Stews/Chili" },
  { rank: 502, dish: "Albondigas Soup", key: "albondigas-soup", category: "Soups/Stews/Chili" },
  { rank: 503, dish: "Ropa Vieja", key: "ropa-vieja", category: "Beef" },
  { rank: 504, dish: "Arroz con Pollo", key: "arroz-con-pollo", category: "Mexican/Tex-Mex" },
  { rank: 505, dish: "Cuban Picadillo", key: "cuban-picadillo", category: "Beef" },
  { rank: 506, dish: "Empanadas (Beef)", key: "empanadas-beef", category: "Mexican/Tex-Mex" },
  { rank: 507, dish: "Pastelón", key: "pastel-n", category: "Casseroles/Bakes" },
  { rank: 508, dish: "Feijoada", key: "feijoada", category: "Soups/Stews/Chili" },
  { rank: 509, dish: "Chicken Yakitori", key: "chicken-yakitori", category: "Asian-American" },
  { rank: 510, dish: "Teriyaki Meatballs", key: "teriyaki-meatballs", category: "Asian-American" },
  { rank: 511, dish: "Sweet Chili Chicken", key: "sweet-chili-chicken", category: "Asian-American" },
  { rank: 512, dish: "Firecracker Chicken", key: "firecracker-chicken", category: "Asian-American" },
  { rank: 513, dish: "Bang Bang Shrimp", key: "bang-bang-shrimp", category: "Asian-American" },
  { rank: 514, dish: "Bang Bang Chicken", key: "bang-bang-chicken", category: "Asian-American" },
  { rank: 515, dish: "Honey Sriracha Chicken", key: "honey-sriracha-chicken", category: "Asian-American" },
  { rank: 516, dish: "Sheet-Pan Teriyaki Chicken and Veg", key: "sheet-pan-teriyaki-chicken-and-veg", category: "Asian-American" },
  { rank: 517, dish: "Baked Coconut Shrimp", key: "baked-coconut-shrimp", category: "Seafood" },
  { rank: 518, dish: "Garlic Butter Shrimp", key: "garlic-butter-shrimp", category: "Seafood" },
  { rank: 519, dish: "Shrimp Creole", key: "shrimp-creole", category: "Soups/Stews/Chili" },
  { rank: 520, dish: "Crawfish Boil", key: "crawfish-boil", category: "Seafood" },
  { rank: 521, dish: "Fried Fish Sandwich", key: "fried-fish-sandwich", category: "Sandwiches/Burgers" },
  { rank: 522, dish: "Po' Boy (Shrimp)", key: "po-boy-shrimp", category: "Sandwiches/Burgers" },
  { rank: 523, dish: "Po' Boy (Roast Beef)", key: "po-boy-roast-beef", category: "Sandwiches/Burgers" },
  { rank: 524, dish: "Muffuletta", key: "muffuletta", category: "Sandwiches/Burgers" },
  { rank: 525, dish: "Grilled Cheese (Loaded/Gourmet)", key: "grilled-cheese-loaded-gourmet", category: "Sandwiches/Burgers" },
  { rank: 526, dish: "Panini (Chicken Pesto)", key: "panini-chicken-pesto", category: "Sandwiches/Burgers" },
  { rank: 527, dish: "Turkey Avocado Wrap", key: "turkey-avocado-wrap", category: "Sandwiches/Burgers" },
  { rank: 528, dish: "Chicken Caesar Wrap", key: "chicken-caesar-wrap", category: "Sandwiches/Burgers" },
  { rank: 529, dish: "Falafel Wrap", key: "falafel-wrap", category: "Middle Eastern" },
  { rank: 530, dish: "Meatball Marinara Bowl", key: "meatball-marinara-bowl", category: "Italian-American" },
  { rank: 531, dish: "Sausage and Kale White Bean Skillet", key: "sausage-and-kale-white-bean-skillet", category: "Pork" },
  { rank: 532, dish: "White Bean and Sausage Stew", key: "white-bean-and-sausage-stew", category: "Soups/Stews/Chili" },
  { rank: 533, dish: "Cassoulet (Simplified)", key: "cassoulet-simplified", category: "Soups/Stews/Chili" },
  { rank: 534, dish: "Chicken Marbella", key: "chicken-marbella", category: "Chicken" },
  { rank: 535, dish: "Balsamic Glazed Chicken", key: "balsamic-glazed-chicken", category: "Chicken" },
  { rank: 536, dish: "Caprese Chicken", key: "caprese-chicken", category: "Italian-American" },
  { rank: 537, dish: "Bruschetta Chicken", key: "bruschetta-chicken", category: "Italian-American" },
  { rank: 538, dish: "Salsa Verde Chicken", key: "salsa-verde-chicken", category: "Mexican/Tex-Mex" },
  { rank: 539, dish: "Salsa Chicken (Baked)", key: "salsa-chicken-baked", category: "Mexican/Tex-Mex" },
  { rank: 540, dish: "Ranch Chicken (Baked)", key: "ranch-chicken-baked", category: "Chicken" },
  { rank: 541, dish: "Bacon-Wrapped Chicken", key: "bacon-wrapped-chicken", category: "Chicken" },
  { rank: 542, dish: "Stuffed Chicken Breast (Spinach-Feta)", key: "stuffed-chicken-breast-spinach-feta", category: "Chicken" },
  { rank: 543, dish: "Stuffed Chicken Breast (Broccoli-Cheddar)", key: "stuffed-chicken-breast-broccoli-cheddar", category: "Chicken" },
  { rank: 544, dish: "Chicken Cheesesteak", key: "chicken-cheesesteak", category: "Sandwiches/Burgers" },
  { rank: 545, dish: "BBQ Chicken Nachos", key: "bbq-chicken-nachos", category: "Mexican/Tex-Mex" },
  { rank: 546, dish: "Buffalo Chicken Sweet Potatoes", key: "buffalo-chicken-sweet-potatoes", category: "Chicken" },
  { rank: 547, dish: "Sausage, Peppers and Onion Hoagie", key: "sausage-peppers-and-onion-hoagie", category: "Sandwiches/Burgers" },
  { rank: 548, dish: "Chicken Parmesan Pasta (One-Pot)", key: "chicken-parmesan-pasta-one-pot", category: "Pasta" },
  { rank: 549, dish: "Slow-Cooker Pot Roast", key: "slow-cooker-pot-roast", category: "Beef" },
  { rank: 550, dish: "Slow-Cooker Chili", key: "slow-cooker-chili", category: "Soups/Stews/Chili" },
  { rank: 551, dish: "Slow-Cooker Beef Stew", key: "slow-cooker-beef-stew", category: "Soups/Stews/Chili" },
  { rank: 552, dish: "Slow-Cooker Pulled Chicken", key: "slow-cooker-pulled-chicken", category: "Chicken" },
  { rank: 553, dish: "Slow-Cooker Chicken Tacos", key: "slow-cooker-chicken-tacos", category: "Mexican/Tex-Mex" },
  { rank: 554, dish: "Slow-Cooker Beef Barbacoa", key: "slow-cooker-beef-barbacoa", category: "Mexican/Tex-Mex" },
  { rank: 555, dish: "Instant-Pot Chicken and Rice", key: "instant-pot-chicken-and-rice", category: "Chicken" },
  { rank: 556, dish: "Instant-Pot Beef and Broccoli", key: "instant-pot-beef-and-broccoli", category: "Asian-American" },
  { rank: 557, dish: "Baked Salmon in Foil", key: "baked-salmon-in-foil", category: "Seafood" },
  { rank: 558, dish: "BBQ Pork Ribs (Oven)", key: "bbq-pork-ribs-oven", category: "Pork" },
];
