-- Row 5 · Block 4 (D-WS9-247 amendment) — the Home card's "Set up my Playlist"
-- CTA hides once tapped. Per-user (a tap on one phone hides it on another),
-- so it is a column on the user, not device storage. A timestamp like its
-- sibling firstPlanCreatedAt: IS NULL is the gate.
--
-- ADDITIVE ONLY: nullable, no default, no backfill. Cloud Run is live against
-- this branch with a client that does not know the column (D-WS9-254); a
-- nullable add is invisible to it. Generated by `prisma migrate diff
-- --from-url $DATABASE_URL --to-schema-datamodel` (no shadow database —
-- D-WS9-251) and applied with `migrate deploy`.

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "playlistCtaTappedAt" TIMESTAMP(3);
