// WS6 AI orchestrator — DB-backed prompt registry with in-memory fallback.
// Per kiwi_ws6_plan.md §3 6a-2 (DB-backed) + 6a-1 (initial in-memory).
//
// Production runAICall flow:
//   1. resolvePromptDescriptorFromDb(key, prisma)  → DB lookup w/ 60s cache
//   2. on success → return { body, defaultModel, defaultMode, version, ... }
//   3. on miss/error → fall back to REGISTRY (in-memory) and log
//
// Why keep the in-memory map?
//   - Defensive: a deployment race where seed hasn't run yet still works.
//   - Test seam: omit `prisma` and the resolver returns in-memory data —
//     no DB stub required for the 12 existing 6a-1 tests.

import { logger } from "../logger";
import type { AICallMode } from "./modes";

// Latest-as-of-2026-05 model strings. These are mirrored into AIPrompt.defaultModel
// rows by the seed (prisma/seeds/aiPrompts.ts); admins can swap per-prompt models
// at runtime by editing the AIPrompt row.
export const MODEL_SONNET = "claude-sonnet-4-6";
export const MODEL_HAIKU = "claude-haiku-4-5-20251001";

export interface PromptDescriptor {
  body: string;
  defaultModel: string;
  defaultMode: AICallMode;
  toolDescription: string;
}

export interface DescriptorWithVersion extends PromptDescriptor {
  // null when descriptor came from the in-memory REGISTRY fallback (no DB row).
  version: number | null;
}

// Placeholder body builder — emits a clearly-marked stub the caller will
// see in logs if it ever reaches the Anthropic API before 6a-3+ replaces it.
const placeholder = (key: string): string =>
  `[PLACEHOLDER for ${key} — replace via 6a-3+ sub-phase]`;

// Per PRD §15.4.2 + WS6-specific additions. Mode + model assignments per
// kiwi_ws6_plan.md §4 (Hybrid Option C). This map is the SOURCE of fallback
// data; the seed in prisma/seeds/aiPrompts.ts mirrors it into the DB.
const REGISTRY: ReadonlyMap<string, PromptDescriptor> = new Map([
  // 6a-3 — Set Preferences wizard
  [
    "wizard.set_preferences.generate",
    {
      body: placeholder("wizard.set_preferences.generate"),
      defaultModel: MODEL_SONNET,
      defaultMode: "tool",
      toolDescription:
        "Generate up to 3 distinct meal-plan candidates from the user's wizard preferences.",
    },
  ],
  // 6a-4 — Tell Kiwi two-step
  [
    "wizard.directed.parse_intent",
    {
      body: placeholder("wizard.directed.parse_intent"),
      defaultModel: MODEL_HAIKU,
      defaultMode: "text",
      toolDescription:
        "Parse the user's free-text plan request into a structured intent.",
    },
  ],
  [
    "wizard.directed.generate",
    {
      body: placeholder("wizard.directed.generate"),
      defaultModel: MODEL_SONNET,
      defaultMode: "tool",
      toolDescription: "Generate plan candidates given a parsed Tell Kiwi intent.",
    },
  ],
  // WS7-5a — wizard candidate expand (Branch B "View plan"). Sonnet tool_use.
  // WS7-5c Block A: now produces details-stage output (ingredients + dish
  // metadata + per-dish macros, NO steps). Steps are generated by
  // wizard.candidate.finalize_steps below at save/activate time.
  [
    "wizard.candidate.expand",
    {
      body: placeholder("wizard.candidate.expand"),
      defaultModel: MODEL_SONNET,
      defaultMode: "tool",
      toolDescription:
        "Expand one wizard candidate plan into per-meal recipe details (ingredients + dish metadata; steps are generated separately at save).",
    },
  ],
  // WS7-5c Block A — wizard.candidate.finalize_steps. Sonnet tool_use.
  // Call #3 of the three-stage wizard: given the details-stage plan
  // (ingredients + per-dish macros), generate per-dish cooking step lists
  // keyed by (mealIndex, dishIndex). Runs BEFORE the activate/save
  // $transaction so the ~Sonnet latency doesn't pressure the 60s tx budget.
  [
    "wizard.candidate.finalize_steps",
    {
      body: placeholder("wizard.candidate.finalize_steps"),
      defaultModel: MODEL_SONNET,
      defaultMode: "tool",
      toolDescription:
        "Generate per-dish cooking step arrays for a details-stage wizard plan, keyed by mealIndex+dishIndex for positional merge.",
    },
  ],
  // PRD §15.4.2 — Cook Now
  [
    "wizard.cook_now.match",
    {
      body: placeholder("wizard.cook_now.match"),
      defaultModel: MODEL_HAIKU,
      defaultMode: "text",
      toolDescription:
        "Match a Cook Now request against the existing meal catalog.",
    },
  ],
  [
    "wizard.cook_now.generate",
    {
      body: placeholder("wizard.cook_now.generate"),
      defaultModel: MODEL_SONNET,
      defaultMode: "tool",
      toolDescription:
        "Generate a fresh recipe when no catalog match exists for Cook Now.",
    },
  ],
  // PRD §15.4.2 — wizard reasoning sidecar
  [
    "wizard.optimization_notes",
    {
      body: placeholder("wizard.optimization_notes"),
      defaultModel: MODEL_HAIKU,
      defaultMode: "text",
      toolDescription:
        "Generate the why-this-works bullets for a plan candidate.",
    },
  ],
  // 6c-1 — Reformat-for-Kiwi pass and import paths
  [
    "import.url.parse_fallback",
    {
      body: placeholder("import.url.parse_fallback"),
      defaultModel: MODEL_SONNET,
      defaultMode: "tool",
      toolDescription:
        "Parse a recipe from raw URL HTML when JSON-LD extraction fails.",
    },
  ],
  [
    "import.image.ocr_parse",
    {
      body: placeholder("import.image.ocr_parse"),
      defaultModel: MODEL_SONNET,
      defaultMode: "tool",
      toolDescription:
        "Parse a recipe from an OCR'd image of a printed recipe.",
    },
  ],
  [
    "import.reformat_for_kiwi",
    {
      body: placeholder("import.reformat_for_kiwi"),
      defaultModel: MODEL_SONNET,
      defaultMode: "text",
      toolDescription:
        "Normalize a raw recipe into Kiwi's canonical Meal/Dish/Step shape with phaseType / parallelGroup.",
    },
  ],
  // 6c-1 — URL-imported recipe scaling helper.
  [
    "recipes.scale_ingredients",
    {
      body: placeholder("recipes.scale_ingredients"),
      defaultModel: MODEL_SONNET,
      defaultMode: "text",
      toolDescription:
        "Scale a recipe's ingredients from one servings count to another, returning friendly cooking measures.",
    },
  ],
  // 6b-5 — Meal Builder Mode A (parse free-text meal description).
  // Text+Zod mode (mirrors 6a-3 wizard plan-gen + 6b-4 step generation —
  // both proven to handle nested schemas without tool_use overhead). Haiku
  // by default; escalate to Sonnet in a 6b-5-fix sub-phase if smoke shows
  // output quality issues.
  [
    "meal_builder.mode_a_parse",
    {
      body: placeholder("meal_builder.mode_a_parse"),
      defaultModel: MODEL_HAIKU,
      defaultMode: "text",
      toolDescription:
        "Parse free-text meal description into structured ingredients and steps.",
    },
  ],
  // WS7-6 G2 — Dish Builder Mode A (parse free-text dish description). The
  // dish twin of meal_builder.mode_a_parse: single-dish output, no sub-dishes
  // (PRD §10.5.8). Same Haiku / text+Zod posture.
  [
    "dish_builder.mode_a_parse",
    {
      body: placeholder("dish_builder.mode_a_parse"),
      defaultModel: MODEL_HAIKU,
      defaultMode: "text",
      toolDescription:
        "Parse free-text dish description into a single structured dish (ingredients + steps).",
    },
  ],
  // 6b-4 — Kiwi-assist checkboxes (Dish Builder + Meal Builder Mode B)
  [
    "meal_builder.assist_ingredients",
    {
      body: placeholder("meal_builder.assist_ingredients"),
      defaultModel: MODEL_HAIKU,
      defaultMode: "text",
      toolDescription:
        "Fill in or generate a dish's ingredient list from the dish name + cuisine + the user's existing entries.",
    },
  ],
  [
    "meal_builder.assist_steps",
    {
      body: placeholder("meal_builder.assist_steps"),
      defaultModel: MODEL_HAIKU,
      defaultMode: "text",
      toolDescription:
        "Generate phase-tagged cooking steps from a dish's ingredient list + cuisine.",
    },
  ],
  // 6d-2 / WS7-8a B2 — Prep the Week narration (BLENDED: code does the math,
  // AI only writes prose).
  [
    "prep.narrate_steps",
    {
      body: placeholder("prep.narrate_steps"),
      defaultModel: MODEL_SONNET,
      defaultMode: "tool",
      toolDescription:
        "Narrate a code-computed Prep the Week step plan into Cook Mode prose (no math, no attribution).",
    },
  ],
  // 6d-1 — Cooking Sequencer
  [
    "sequencer.step_ordering",
    {
      body: placeholder("sequencer.step_ordering"),
      defaultModel: MODEL_SONNET,
      defaultMode: "tool",
      toolDescription:
        "Order steps from multiple dishes into a single parallel-execution sequence.",
    },
  ],
  // 6b-3 — plan-level macro recalc
  [
    "macros.weighting_rules",
    {
      body: placeholder("macros.weighting_rules"),
      defaultModel: MODEL_HAIKU,
      defaultMode: "text",
      toolDescription:
        "Recalculate plan-level daily macro averages per PRD §11.7 weighting rules.",
    },
  ],
  // 6b-2 — Simple Dish macros AI
  [
    "nutrition.ingredient_estimate",
    {
      body: placeholder("nutrition.ingredient_estimate"),
      defaultModel: MODEL_HAIKU,
      defaultMode: "text",
      toolDescription: "Estimate per-serving macros from an ingredient list.",
    },
  ],
  // 6c-6 — predictive grocery-add categorization
  [
    "grocery.recurring_item_categorize",
    {
      body: placeholder("grocery.recurring_item_categorize"),
      defaultModel: MODEL_HAIKU,
      defaultMode: "text",
      toolDescription:
        "Categorize a free-text grocery item into a section + canonical name.",
    },
  ],
  // 6c-4 Block B — Haiku gap-fill for Ingredient.purchaseUnit/Quantity/Display.
  // Called once per ingredient missing purchase metadata; result written back
  // to the Ingredient row so subsequent plans hit the cache.
  [
    "grocery.gap_fill_purchase_size",
    {
      body: placeholder("grocery.gap_fill_purchase_size"),
      defaultModel: MODEL_HAIKU,
      defaultMode: "text",
      toolDescription:
        "Map a recipe ingredient need to its standard grocery-store purchase size + display label.",
    },
  ],
  // 6c-4 Block B — Sonnet final polish over the deterministic + gap-filled
  // grocery list. Refines display names, reconciles unit-mismatch survivors,
  // reassigns 'extras' bucket items. Preserves staple/recurring flags exactly.
  [
    "grocery.generate_list",
    {
      body: placeholder("grocery.generate_list"),
      defaultModel: MODEL_SONNET,
      defaultMode: "text",
      toolDescription:
        "Finalize a meal plan grocery list: refine display names, reconcile unit mismatches, reassign extras-bucketed items to correct sections. Preserves staple/recurring flags exactly.",
    },
  ],
  // 6b-1 — Find Similar AI semantic similarity (WS6 addition)
  [
    "meals.find_similar",
    {
      body: placeholder("meals.find_similar"),
      defaultModel: MODEL_HAIKU,
      defaultMode: "text",
      toolDescription: "Rank candidate meals by similarity to a source meal.",
    },
  ],
]);

export class UnknownPromptKeyError extends Error {
  constructor(key: string) {
    super(`Unknown prompt key: ${key}`);
    this.name = "UnknownPromptKeyError";
  }
}

// Synchronous registry lookup — kept for any legacy caller that hasn't
// migrated to the async DB-backed path. New callers should prefer
// resolvePromptDescriptorFromDb.
export function resolvePromptDescriptor(key: string): PromptDescriptor {
  const descriptor = REGISTRY.get(key);
  if (!descriptor) throw new UnknownPromptKeyError(key);
  return descriptor;
}

export function resolvePromptBody(key: string): string {
  return resolvePromptDescriptor(key).body;
}

// Naive {{var}} substitution. Caller passes a flat record; values are
// JSON-stringified if not strings. Missing keys are left as-is so they
// surface during prompt-iteration debugging instead of being silently empty.
export function renderPromptBody(
  body: string,
  vars: Record<string, unknown>,
): string {
  return body.replace(/\{\{(\w+)\}\}/g, (match, name: string) => {
    if (!(name in vars)) return match;
    const v = vars[name];
    return typeof v === "string" ? v : JSON.stringify(v);
  });
}

// ── Prisma surface ──────────────────────────────────────────────────────
// Minimal structural type. Lets tests inject a stub without depending on
// the full PrismaClient type or any Prisma runtime.

export interface PromptVersionRow {
  body: string;
  version: number;
  isActive: boolean;
}

export interface AIPromptRow {
  id: string;
  key: string;
  defaultModel: string;
  defaultMode: AICallMode;
  // Optional so the real PrismaClient.findUnique (without include) is also
  // assignable. The resolver always queries with include and treats absence
  // as a fallback path.
  versions?: PromptVersionRow[];
}

export interface SystemSettingRow {
  key: string;
  value: unknown;
}

// Structural type — broader on inputs so the real PrismaClient is assignable
// (Prisma's typed where/include are stricter than ours, which is fine), and
// exact-enough on returned values so consumers get the columns they need.
// `any` on args is intentional; tightening it would break PrismaClient
// assignment without giving callers anything they don't already get from the
// returned row types.
export interface PrismaLike {
  aIPrompt: {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    findUnique(args: any): Promise<AIPromptRow | null>;
  };
  systemSetting: {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    findUnique(args: any): Promise<SystemSettingRow | null>;
  };
  lLMCallLog: {
    create(args: { data: LLMCallLogCreateData }): Promise<unknown>;
  };
}

export interface LLMCallLogCreateData {
  promptKey: string;
  promptVersion: number | null;
  model: string;
  mode: AICallMode;
  userId: string | null;
  latencyMs: number;
  inputTokens: number;
  outputTokens: number;
  costEstimateUsd: number;
  retryCount: number;
  success: boolean;
  failureReason: string | null;
}

// ── 60-second TTL cache ─────────────────────────────────────────────────
// Per PRD §15.4.4. Per-key entries; no eviction beyond TTL since the keyset
// is bounded (~17 prompts + ~4 model rates).

const CACHE_TTL_MS = 60_000;

interface CacheEntry<T> {
  value: T;
  expiresAt: number;
}

const promptCache = new Map<string, CacheEntry<DescriptorWithVersion>>();
const rateCache = new Map<string, CacheEntry<ModelRate>>();

function cacheGet<T>(
  cache: Map<string, CacheEntry<T>>,
  key: string,
): T | null {
  const entry = cache.get(key);
  if (!entry) return null;
  if (entry.expiresAt < Date.now()) {
    cache.delete(key);
    return null;
  }
  return entry.value;
}

function cacheSet<T>(
  cache: Map<string, CacheEntry<T>>,
  key: string,
  value: T,
): void {
  cache.set(key, { value, expiresAt: Date.now() + CACHE_TTL_MS });
}

// Test helper — clear both caches between tests.
export function _resetRegistryCaches(): void {
  promptCache.clear();
  rateCache.clear();
}

// ── DB-backed resolution ────────────────────────────────────────────────

export async function resolvePromptDescriptorFromDb(
  key: string,
  prismaClient: PrismaLike | null,
): Promise<DescriptorWithVersion> {
  const cached = cacheGet(promptCache, key);
  if (cached) return cached;

  // Validate key against in-memory registry first so unknown keys throw the
  // same error whether the DB is reachable or not. Programmer-error path.
  const fallback = REGISTRY.get(key);
  if (!fallback) throw new UnknownPromptKeyError(key);

  if (prismaClient) {
    try {
      const row = await prismaClient.aIPrompt.findUnique({
        where: { key },
        include: { versions: { where: { isActive: true }, take: 1 } },
      });
      const active = row?.versions?.[0];
      if (row && active) {
        const value: DescriptorWithVersion = {
          body: active.body,
          defaultModel: row.defaultModel,
          defaultMode: row.defaultMode,
          // toolDescription stays in code — it's caller-facing metadata,
          // not user-editable prompt content. Sourced from REGISTRY.
          toolDescription: fallback.toolDescription,
          version: active.version,
        };
        cacheSet(promptCache, key, value);
        return value;
      }
      logger.warn(
        { event: "prompt_resolve", key },
        "AI prompt not found in DB — using in-memory fallback",
      );
    } catch (err) {
      logger.error(
        { event: "prompt_resolve", key, err },
        "AI prompt DB lookup failed — using in-memory fallback",
      );
    }
  }

  // Fallback: in-memory registry. Don't cache (so the next call retries DB).
  return { ...fallback, version: null };
}

// ── Cost estimation ─────────────────────────────────────────────────────

export interface ModelRate {
  inputPerMtokUsd: number;
  outputPerMtokUsd: number;
}

// Hardcoded fallback rates. The seed mirrors these into SystemSetting rows
// (prisma/seeds/systemSettings.ts). Production reads from the DB; if that
// fails, we fall back here so cost calculation never throws.
const FALLBACK_MODEL_RATES: Record<string, ModelRate> = {
  "claude-sonnet-4-6": { inputPerMtokUsd: 3, outputPerMtokUsd: 15 },
  "claude-haiku-4-5-20251001": { inputPerMtokUsd: 1, outputPerMtokUsd: 5 },
};

export async function getModelRate(
  model: string,
  prismaClient: PrismaLike | null,
): Promise<ModelRate> {
  const cached = cacheGet(rateCache, model);
  if (cached) return cached;

  if (prismaClient) {
    try {
      const [inputRow, outputRow] = await Promise.all([
        prismaClient.systemSetting.findUnique({
          where: { key: `ai.model_rate.${model}.input_per_mtok` },
        }),
        prismaClient.systemSetting.findUnique({
          where: { key: `ai.model_rate.${model}.output_per_mtok` },
        }),
      ]);
      if (inputRow && outputRow) {
        const value: ModelRate = {
          inputPerMtokUsd: Number(inputRow.value),
          outputPerMtokUsd: Number(outputRow.value),
        };
        cacheSet(rateCache, model, value);
        return value;
      }
      logger.warn(
        { event: "model_rate_lookup", model },
        "Model rate not found in DB — using in-memory fallback",
      );
    } catch (err) {
      logger.error(
        { event: "model_rate_lookup", model, err },
        "Model rate DB lookup failed — using in-memory fallback",
      );
    }
  }

  // Fallback: hardcoded rates. Unknown models → 0 (don't fabricate cost).
  return FALLBACK_MODEL_RATES[model] ?? { inputPerMtokUsd: 0, outputPerMtokUsd: 0 };
}

export function estimateCostUsdFromRate(
  rate: ModelRate,
  inputTokens: number,
  outputTokens: number,
): number {
  const inputCost = (inputTokens / 1_000_000) * rate.inputPerMtokUsd;
  const outputCost = (outputTokens / 1_000_000) * rate.outputPerMtokUsd;
  return inputCost + outputCost;
}

// Sync convenience helper that uses the fallback rates table. Production
// runtime uses estimateCostUsdFromRate after fetching via getModelRate so
// costs reflect SystemSetting overrides; this helper is for tests and any
// codepath where DB access isn't available.
export function estimateCostUsd(
  model: string,
  inputTokens: number,
  outputTokens: number,
): number {
  const rate = FALLBACK_MODEL_RATES[model];
  if (!rate) return 0;
  return estimateCostUsdFromRate(rate, inputTokens, outputTokens);
}

// Test/diagnostic helper — list registered keys.
export function listPromptKeys(): readonly string[] {
  return Array.from(REGISTRY.keys());
}
