-- Row 8 · Block 1 — Instacart Developer Platform link-out. The three columns
-- record the most recent shopping-list page Kiwi minted for a list (URL, when,
-- and Instacart's expiry = linkedAt + 30 days). Written on every successful
-- link; a later tap overwrites. `status` is untouched: link-out cannot know an
-- order happened, so `ordered` stays reserved and unused.
--
-- ADDITIVE ONLY: three nullable columns, no default, no backfill. Cloud Run is
-- live against this branch (min-instances=1) with a client that does not know
-- the columns; a nullable add is invisible to it. Generated by `prisma migrate
-- diff --from-url $DATABASE_URL --to-schema-datamodel` (no shadow database —
-- D-WS9-251) and applied with `migrate deploy`.

-- AlterTable
ALTER TABLE "grocery_lists" ADD COLUMN     "instacartLinkExpiresAt" TIMESTAMP(3),
ADD COLUMN     "instacartLinkUrl" TEXT,
ADD COLUMN     "instacartLinkedAt" TIMESTAMP(3);
